server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
db:
  driverClass: org.postgresql.Driver
  url: 'jdbc:postgresql://localhost:5433/testdb'
  user: root
  password: root
swagger:
  resourcePackage: com.test.api
  customJavascript: myassets/customJavascript.js
  title: Test Api
  version: '${BUILD_VERSION:- 1.0}'
logging:
  level: '${LOG_LEVEL:-INFO}'
  appenders:
    - type: console